services:
  kg-api:
    build: .
    container_name: kg-mlops-service
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    command: ["./scripts/run_pipeline.sh"]
